/** Theme = structural bar role (Hook, Verse, etc.) — user-editable */
export type Theme = { id: string; name: string; color: string };

export const DEFAULT_THEMES: Theme[] = [
  { id: '1', name: 'Hook', color: '#ec4899' },
  { id: '2', name: 'Verse', color: '#8b5cf6' },
  { id: '3', name: 'Bridge', color: '#10b981' },
  { id: '4', name: 'Punchline', color: '#ef4444' },
];

/** Character: family + one concrete tag */
export type CharacterFamily = { id: string; name: string; tags: string[] };

export const CHARACTER_FAMILIES: CharacterFamily[] = [
  {
    id: 'power',
    name: 'Power / Authority',
    tags: [
      'Elite',
      'Dominant',
      'Unstoppable',
      'Commanding',
      'Strategic',
      'Relentless',
      'Decisive',
      'Influential',
      'Fearless',
      'Precise',
    ],
  },
  {
    id: 'curiosity',
    name: 'Curiosity / Intrigue',
    tags: [
      'Hidden',
      'Untold',
      'Rare',
      'Secret',
      'Forbidden',
      'Overlooked',
      'Unseen',
      'Unexpected',
      'Little-known',
      'Mysterious',
    ],
  },
  {
    id: 'luxury',
    name: 'Luxury / Status',
    tags: [
      'Premium',
      'Exclusive',
      'High-end',
      'Refined',
      'Sophisticated',
      'Opulent',
      'First-class',
      'Polished',
      'Elevated',
      'Lavish',
    ],
  },
  {
    id: 'growth',
    name: 'Growth / Transformation',
    tags: [
      'Breakthrough',
      'Evolving',
      'Next-level',
      'Upgraded',
      'Reinvented',
      'Sharpened',
      'Optimized',
      'Transformed',
      'Refined',
      'Elevated',
    ],
  },
  {
    id: 'simplicity',
    name: 'Simplicity / Clarity',
    tags: [
      'Effortless',
      'Simple',
      'Clean',
      'Streamlined',
      'Direct',
      'Clear-cut',
      'Practical',
      'Minimal',
      'Focused',
      'Accessible',
    ],
  },
  {
    id: 'energy',
    name: 'Energy / Excitement',
    tags: [
      'Explosive',
      'Electric',
      'Dynamic',
      'Fast-paced',
      'High-impact',
      'Game-changing',
      'Bold',
      'Intense',
      'Powerful',
      'Energizing',
    ],
  },
  {
    id: 'trust',
    name: 'Trust / Reliability',
    tags: [
      'Proven',
      'Consistent',
      'Reliable',
      'Tested',
      'Trusted',
      'Solid',
      'Dependable',
      'Authentic',
      'Verified',
      'Credible',
    ],
  },
  {
    id: 'innovation',
    name: 'Innovation / Edge',
    tags: [
      'Cutting-edge',
      'Advanced',
      'Revolutionary',
      'Disruptive',
      'Futuristic',
      'Smart',
      'Intelligent',
      'Adaptive',
      'Groundbreaking',
      'Inventive',
    ],
  },
  {
    id: 'emotion',
    name: 'Emotion / Connection',
    tags: [
      'Genuine',
      'Real',
      'Raw',
      'Honest',
      'Personal',
      'Relatable',
      'Inspiring',
      'Empowering',
      'Uplifting',
      'Meaningful',
    ],
  },
  {
    id: 'scarcity',
    name: 'Scarcity / Urgency',
    tags: [
      'Limited',
      'Rare',
      'Time-sensitive',
      'Exclusive',
      'Now-only',
      'Closing',
      'Final',
      'Hard-to-get',
      'In-demand',
      'Once-in-a-lifetime',
    ],
  },
];

/** Art / literary device */
export const ART_DEVICES: string[] = [
  'Metaphor',
  'Simile',
  'Personification',
  'Anaphora',
  'Alliteration',
  'Assonance',
  'Imagery',
  'Hyperbole',
  'Irony',
  'Symbolism',
  'Wordplay',
  'Parallelism',
  'Rhetorical question',
  'Contrast',
  'Repetition',
];

/** “What am I selling” — Ogilvy-style focus */
export const SELL_FOCUS_OPTIONS: string[] = [
  'Lifestyle',
  'Narrative',
  'Money / success',
  'Status',
  'Aspiration',
  'Identity',
  'Proof / credibility',
  'Urgency',
  'Fear / loss',
  'Desire / pleasure',
  'Transformation',
  'Community / belonging',
  'Freedom',
  'Power',
  'Love / connection',
];

export type GrammyGoal = { id: string; name: string };

/** Default 2027 Grammy targets — user can add more in-app */
export const DEFAULT_GRAMMY_GOALS: GrammyGoal[] = [
  { id: 'g-record', name: 'Win Record of the Year' },
  { id: 'g-album', name: 'Win Album of the Year' },
  { id: 'g-song', name: 'Win Song of the Year' },
  { id: 'g-new', name: 'Best New Artist' },
  { id: 'g-swoty', name: 'Songwriter of the Year, Non-Classical' },
  { id: 'g-rnb-perf', name: 'Win Best R&B Performance' },
  { id: 'g-trad-rnb', name: 'Win Best Traditional R&B Performance' },
  { id: 'g-rnb-song', name: 'Win Best R&B Song' },
  { id: 'g-prog-rnb-album', name: 'Win Best Progressive R&B Album' },
  { id: 'g-rnb-album', name: 'Win Best R&B Album' },
  { id: 'g-rap-perf', name: 'Win Best Rap Performance' },
  { id: 'g-melodic-rap', name: 'Win Best Melodic Rap Performance' },
  { id: 'g-rap-song', name: 'Win Best Rap Song' },
  { id: 'g-rap-album', name: 'Win Best Rap Album' },
  { id: 'g-spoken', name: 'Win Best Spoken Word Poetry Album' },
];
